### ISSUE TITLE
Problems Building on Mac (with workaround)

### ISSUE THREAD

**Issue by markmsmith** [Gladdy/EasyOpenCL#2]
Hey, I just thought I'd give you a heads up that I encountered a few problems running this on a 2015 MacBook Pro, OS X 10.10.5 (Yoesmite), Intel Iris Pro.

First it would blow up with various errors about not finding `CL/cl.h`.
I fixed that by editing `easyopencl.h` and `boundvalue.h` to import `OpenCL/cl.h` instead of `CL/cl.h`

Next there were errors about  `uint` and `clCreateCommandQueueWithProperties` being undefined when running the `make` command.
I fixed that by editing `easyopencl.h` to add the following, below the import for cl.h:

``` c++
typedef unsigned int uint;
#define clCreateCommandQueueWithProperties clCreateCommandQueue
```

Lastly, I had to change `simplekernel.cl`, modifying the function declaration to include the output array (or it complains about `output` being an undeclared identifier):

``` c++
__kernel void simplekernel( __global int* input
                          , const int singlevalue
                          , __global int* output )
```

I'm not much of a C++ developer, so maybe there's a better way, but this at least got the example program running for me.  Hopefully this is of some help.

**Comment by markmsmith** [comment]
For anyone more knowledgable investigating `uint` not being defined, it appears to be declared in the following places on my system:
- /System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/2.0/include/cl_kernel.h
- /System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/2.0/include/cl_kernel_shared.h
- /System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h
- /System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel_shared.h

The file `/System/Library/Frameworks/OpenCL.framework/module.map` contains the following:

```
framework module OpenCL [extern_c] [system] {
  umbrella header "opencl.h"

  export *
  module * { export * }

  exclude header "cl_kernel.h"
  exclude header "gcl_priv.h"
}
```

which makes is seem like at least cl_kernel_shared.h should still be exported, so I don't know if `easyopencl.h` should be importing that or that points to something else that should be changed.

**Comment by Gladdy** [comment]
(1) Currently, I don't have a Mac to test the '#include <CL/cl.h>' problems with and furthermore I'm not very familiar with the OSX framework functionality. I  In order to fix it I have created a separate header file (keeping it DRY) 'opencl-crossplatform.h' which contains an #ifdef switch, including a different header when you're on a Mac (`OpenCL/opencl.h`) instead of on Linux (and possibly Windows), `CL/opencl.h`. Could you check whether this does work properly on OS X without any modifications?

(2) Apparently `uint` is not part of the C++ standard - `unsigned int` is so I have added the typedef to the header files for compatibility.

(3) I have added an #ifdef switch for clCreateCommandQueueWithProperties. OpenCL 2.0 uses 'clCreateCommandQueueWithProperties' whereas older versions (1.1 and 1.2) use 'clCreateCommandQueue', but the arguments are the same.

(4) simplekernel.cl and main.cpp have been updated/rectified - some code got out of sync between updating the README.md and the examples themselves.

**Comment by hi-abhi** [comment]
Everything works here on OS X 10.10.5

**Comment by markmsmith** [comment]
I've updated and the fixes work great for me, thanks.
