### ISSUE TITLE
Testing Framework throws error with less trivial example

### ISSUE THREAD

**Issue by zynga-jpetersen** [Gladdy/EasyOpenCL#5]
Greetings, this looks like a great framework to simplify all the OpenCL nonsense, unfortunately it would be great to have some more complex examples  or additional documentation.

I got the example built and then tried to make it more complex, so changed it in simple.cpp:

```
auto& square = framework.load("squarefloat");
std::vector<float> list = { 1.1, 2.2, 3.3, 4.4, 5.5, 11.0 };
for( int i = 0; i < 10000000; i++ ) {
      list.push_back( list[  i % 5 ] );
}
square.bindInput(0, list);
```

After rebuilding this gave me the following error: 

./simple
Error: Running kernel square float  CL_INVALID_WORK_GROUP_SIZE

I'm sure this is something I'm doing, but given the current documentation, I'm unable to find what your framework is expecting me to set to increase the work group size. I'm on a mac if that matters. Thanks!

**Comment by Gladdy** [comment]
Better documentation, as in more examples (for the main use cases of GPUs, matrix operations/deep learning and image processing)  and some actual doc pages (not just in the source), eg. doxygen or the likes are almost at the top of of my todo list - the #1 is your actual described problem.

Some history on your issue: As initial (temporary) implementation, I devised the most simple alternative, which puts all the work in a single work group. I didn't want to bother the user with setting work group sizes by hand. This has the unfortunate side effect that for kernels beyond the smallest, the maximum work group size gets exceeded. I have seen this value as low as 256 (on an old GPU) to 8192, when executing on a CPU with Intels OpenCL drivers. As can be easily understood this is hardly ideal (for the bare minimal learning experience it might not matter so much), but it renders the framework unusable for any real-world tasks.

As a real (permanent) solution I'm implementing automatic detection of local and global work group sizes which tries to obtain maximum speed. This approach has two main issues: 1) Even though OpenCL is cross-platform, you are still running on separate devices with different hardware and different granularity levels. What might run very well on an AMD card might run very slowly on NVIDIA and vice versa. This takes some tinkering on my end but it's not an insurmountable problem. 2) The main issue is that the choices the framework might make for speed could possibly affect the code required in the kernel, eg. if it chooses to have some threads remain idle whilst still part of the kernel this should be reflected in the user-written kernel code. I do have a solution for this as well - generating kernel stubs. You specify the inputs and outputs you want in C++, as if you'd run the kernel but instead of kernel.evaluate() you call kernel.generateStubs(), which would create all the necessary .cl files with the proper function definitions in which you merely need to write your own functionality. Afterwards you can use those in your real program. There are still some kinks to be worked out but I'm getting there. 

I feel like this real solution does make things a lot easier for the user but it clearly remains OpenCL - I wouldn't want to abstract the low-level stuff so much that it is not noticeable any more and you could just run maps and folds over your data with lambda functions.

Anyway, that was a large wall of text but I hope it was somewhat informative. In short, I know about the problem you've described and I'm well on my way of fixing it. If you have any further questions to ask I'll be happy to answer them and if you have any further feedback it'd be most welcome.

Regards,
Martijn
